### ISSUE TITLE
GDIW Incompatability

### ISSUE THREAD

**Issue by OvermindDL1** [LovelySanta/FactorioMod-MoreScience-ScienceCostTweakerExtension#4]
When using the GDIW (Gah! Durn it Water! or something like that) mod (which copies recipes that use fluids to rearrange the fluids for all possible combinations) it seems to copy the original More Science version of the recipes instead of the MoreScience-ScienceCostTweaker version, thus giving the player an option for the significantly reduced cost version.  Likely an ordering issue in mod loading.

**Comment by LovelySanta** [comment]
This is indeed a loading oder issue. Nothing I can do about it, becose my side needs to wait on SCT to be initialized. The solution is on GDIW's side adding dependency on this mod, or implement a specific loading for my mod.

Nothing wrong with this on my end, nothing I can do about it (becose of SCT itself)

Kind regarnds
lovely_santa
