### ISSUE TITLE
Science Packs Unused in SCT

### ISSUE THREAD

**Issue by HellWatcher** [LovelySanta/FactorioMod-MoreScience-ScienceCostTweakerExtension#6]
Orange and Cyan science packs are unused in SCT. It breaks recipe continuity having these packs still enabled.

**Comment by LovelySanta** [comment]
can you upload a save file of yours?

**Comment by HellWatcher** [comment]
Here is the saved game MPmap and the factorio-extended machines mod in this link has a tiny edit for some lab graphics `prototypes\entity\lab.lua lab.on_animation.layers lab.off_animation.layers` commented out that didn't want to load during startup. [Dropbox link](https://www.dropbox.com/sh/47esiin62exio29/AADAg0T6PYDLsIbkUOSoS2Gca?dl=0)

**Comment by LovelySanta** [comment]
Metalfan told me it did work, but just didn't have dedicated intermediate ingredients, right? If this is the case, it is working as intended, but I want to add in some intermediates to it in the future.

**Comment by HellWatcher** [comment]
Ok cool
